# Configura tus credenciales de Supabase
SUPABASE_URL = "https://cbpadqwmmmqtqaaticeg.supabase.co" 
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicGFkcXdtbW1xdHFhYXRpY2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDMyODUsImV4cCI6MjA1NjQxOTI4NX0.WIjfKHwrUcB2BXsfeG9l_wDuo-GbL8h3e0ksCNjmaoM" 
